--- #YAML:1.0
name:               SDLx-Coro-Widget-Controller
version:            0.01
abstract:           Event loop with Coro yummyness
author:
    - Brock Wilcox <awwaiid@thelackthereof.org>
license:            perl
distribution_type:  module
configure_requires:
    EV:                   0
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Coro:                 4.37
    Coro::EV:             0
    SDLx::Widget::Controller:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02 and then some
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
